services:
  db:
    image: postgres:17-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgressql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${PG_VOLUME}:/var/lib/postgressql/data/pgdata
    networks:
      - atprotofeed
  feedgen:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:${FEEDGEN_PORT} # Map the service port to the host
    environment:
      - DATABASE_URL=$DOCKER_DATABASE_URL
      - FEEDGEN_SUBSCRIPTION_ENDPOINT=$FEEDGEN_SUBSCRIPTION_ENDPOINT
      - FEEDGEN_HOSTNAME=$FEEDGEN_HOSTNAME
      - FEEDGEN_PUBLISHER_DID=$FEEDGEN_PUBLISHER_DID
      - FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY=$FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY
    networks:
      - atprotofeed
networks:
  atprotofeed:
