export const Timezones = {
  "New Zealand Daylight Time": "NZDT",
  "International Date Line, East": "IDLE",
  "New Zealand Standard Time": "NZST",
  "New Zealand Time": "NZT",
  "Australia Eastern Summer Standard Time": "AESST",
  "Central Australia Summer Standard Time": "ACSST",
  "Central Australia Daylight Savings Time": "CADT",
  "South Australian Daylight Time": "SADT",
  "Australia Eastern Standard Time": "AEST",
  "East Australian Standard Time": "EAST",
  "Guam Standard Time, USSR Zone 9": "GST",
  "Melbourne, Australia": "LIGT",
  "South Australia Standard Time": "SAST",
  "Central Australia Standard Time": "CAST",
  "Australia Western Summer Standard Time": "AWSST",
  "Japan Standard Time, USSR Zone 8": "JST",
  "Korea Standard Time": "KST",
  "Kwajalein Time": "MHT",
  "West Australian Daylight Time": "WDT",
  "Moluccas Time": "MT",
  "Australia Western Standard Time": "AWST",
  "China Coastal Time": "CCT",
  "West Australian Daylight Time-A": "WADT",
  "West Australian Standard Time": "WST",
  "Java Time": "JT",
  "Almaty Summer Time": "ALMST",
  "West Australian Standard Time-A": "WAST",
  "Christmas (Island) Time": "CXT",
  "Almaty Time": "ALMT",
  "Mawson (Antarctica) Time": "MAWT",
  "Indian Chagos Time": "IOT",
  "Maldives Island Time": "MVT",
  "Kerguelen Time": "TFT",
  "Afghanistan Time": "AFT",
  "Antananarivo Savings Time": "EAST",
  "Mauritius Island Time": "MUT",
  "Reunion Island Time": "RET",
  "Mahe Island Time": "SCT",
  "Iran Time": "IT",
  "Antananarivo, Comoro Time": "EAT",
  "Baghdad Time": "BT",
  "Eastern Europe Daylight Savings Time": "EETDST",
  "Hellas Mediterranean Time": "HMT",
  "British Double Standard Time": "BDST",
  "Central European Savings Time": "CEST",
  "Central European Daylight Savings Time": "CETDST",
  "Eastern Europe, USSR Zone 1": "EET",
  "French Winter Time": "FWT",
  "Israel Standard Time": "IST",
  "Middle Europe Summer Time": "MEST",
  "Middle Europe Daylight Time": "METDST",
  "Swedish Summer Time": "SST",
  "British Summer Time": "BST",
  "Central European Time": "CET",
  "Dansk Normal Tid": "DNT",
  "French Summer Time": "FST",
  "Middle Europe Time": "MET",
  "Middle Europe Winter Time": "MEWT",
  "Middle Europe Zone": "MEZ",
  "Norway Standard Time": "NOR",
  "Seychelles Time": "SET",
  "Swedish Winter Time": "SWT",
  "Western Europe Daylight Savings Time": "WETDST",
  "Greenwich Mean Time": "GMT",
  "Universal Time": "UT",
  "Universal Time, Coordinated": "UTC",
  "Same as UTC": "Z",
  "Western Europe": "WET",
  "West Africa Time": "WAT",
  "Newfoundland Daylight Time": "NDT",
  "Atlantic Daylight Time": "ADT",
  Unknown: "AWT",
  "Newfoundland Standard Time": "NFT",
  "Atlantic Standard Time (Canada)": "AST",
  "Atlantic/Porto Acre Summer Time": "ACST",
  "Atlantic/Porto Acre Standard Time": "ACT",
  "Eastern Daylight Time": "EDT",
  "Central Daylight Time": "CDT",
  "Eastern Standard Time": "EST",
  "Central Standard Time": "CST",
  "Mountain Daylight Time": "MDT",
  "Mountain Standard Time": "MST",
  "Pacific Daylight Time": "PDT",
  "Alaska Daylight Time": "AKDT",
  "Pacific Standard Time": "PST",
  "Yukon Daylight Time": "YDT",
  "Alaska Standard Time": "AKST",
  "Hawaii/Alaska Daylight Time": "HDT",
  "Yukon Standard Time": "YST",
  "Alaska-Hawaii Standard Time": "AHST",
  "Hawaii Standard Time": "HST",
  "Central Alaska Time": "CAT",
  "Nome Time": "NT",
  "International Date Line, West": "IDLW",
} as const;

export type TimeZone = keyof typeof Timezones;
export type TimeCode = (typeof Timezones)[TimeZone];
